# Setup
setup: simclr

train_dir: KenyaModel_6CLS_153_exp

# Model
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 256

# Dataset
train_db_name: KenyaDataset
num_classes: 6

# Loss
criterion: simclr
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 500
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.01
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 32
num_workers: 8


# Transformations
augmentation_strategy: custom_aug
augmentation_kwargs:
   random_resized_crop:
      size: 153
      scale: [0.2, 1.0]
      ratio: [0.75,1.3333]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: [0.5,2]
      contrast: [2,7]
      saturation: 0
      hue: 0
   normalize:
      mean: [0.4049, 0.3090, 0.2831]
      std: [0.2702, 0.1792, 0.1679]

transformation_kwargs:
   crop_size: 153
   normalize:
      mean: [0.4049, 0.3090, 0.2831]
      std: [0.2702, 0.1792, 0.1679]
